### PR TITLE
52738-track-users-learned-words

### PR DESCRIPTION
**Pull request by l0ngvh**
## Related Tickets
- [#52738](https://edu-redmine.sun-asterisk.vn/issues/52738)

## WHAT (optional)
- I added a checkbox that user can check when they have finish learning a words

## HOW
- I added an association between users and words to keep track which user has learned which word, than add an ajax handling to the controller handle the add / remove association.

## WHY (optional)
- Because if I not handle the ajax, the page will be reload each time user check the box

## Evidence (Screenshot or Video)
image
image

### CODE REVIEW

**Review by htpt2910 — COMMENTED** [review]
okleee

**Comment by l0ngvh** [comment]
ready

**Review by htpt2910 — COMMENTED** [review]
cmt

**Comment by l0ngvh** [comment]
ready

**Pull request merged**
