### PR TITLE
52078 admin add new course

### PR DESCRIPTION
**Pull request by htpt2910**
## Related Tickets
- [#52078](https://edu-redmine.sun-asterisk.vn/issues/52078)

## WHAT (optional)
- Add add course 
- Fix show course order

## Evidence (Screenshot or Video)
Screen Shot 2022-08-17 at 17 15 16
Screen Shot 2022-08-17 at 17 15 27
Screen Shot 2022-08-17 at 17 15 42

### CODE REVIEW

**Comment by htpt2910** [comment]
ready

**Comment by htpt2910** [comment]
ready

**Review by l0ngvh — COMMENTED** [review]
Okeeee

**Review by ghost — COMMENTED** [review]
merged

**Pull request merged**
